/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apress_wavplayer_MainActivity_PlayTask */

#ifndef _Included_com_apress_wavplayer_MainActivity_PlayTask
#define _Included_com_apress_wavplayer_MainActivity_PlayTask
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
