/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apress_threads_MainActivity */

#ifndef _Included_com_apress_threads_MainActivity
#define _Included_com_apress_threads_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_apress_threads_MainActivity_MODE_PRIVATE
#define com_apress_threads_MainActivity_MODE_PRIVATE 0L
#undef com_apress_threads_MainActivity_MODE_WORLD_READABLE
#define com_apress_threads_MainActivity_MODE_WORLD_READABLE 1L
#undef com_apress_threads_MainActivity_MODE_WORLD_WRITEABLE
#define com_apress_threads_MainActivity_MODE_WORLD_WRITEABLE 2L
#undef com_apress_threads_MainActivity_MODE_APPEND
#define com_apress_threads_MainActivity_MODE_APPEND 32768L
#undef com_apress_threads_MainActivity_MODE_MULTI_PROCESS
#define com_apress_threads_MainActivity_MODE_MULTI_PROCESS 4L
#undef com_apress_threads_MainActivity_BIND_AUTO_CREATE
#define com_apress_threads_MainActivity_BIND_AUTO_CREATE 1L
#undef com_apress_threads_MainActivity_BIND_DEBUG_UNBIND
#define com_apress_threads_MainActivity_BIND_DEBUG_UNBIND 2L
#undef com_apress_threads_MainActivity_BIND_NOT_FOREGROUND
#define com_apress_threads_MainActivity_BIND_NOT_FOREGROUND 4L
#undef com_apress_threads_MainActivity_BIND_ABOVE_CLIENT
#define com_apress_threads_MainActivity_BIND_ABOVE_CLIENT 8L
#undef com_apress_threads_MainActivity_BIND_ALLOW_OOM_MANAGEMENT
#define com_apress_threads_MainActivity_BIND_ALLOW_OOM_MANAGEMENT 16L
#undef com_apress_threads_MainActivity_BIND_WAIVE_PRIORITY
#define com_apress_threads_MainActivity_BIND_WAIVE_PRIORITY 32L
#undef com_apress_threads_MainActivity_BIND_IMPORTANT
#define com_apress_threads_MainActivity_BIND_IMPORTANT 64L
#undef com_apress_threads_MainActivity_BIND_ADJUST_WITH_ACTIVITY
#define com_apress_threads_MainActivity_BIND_ADJUST_WITH_ACTIVITY 64L
#undef com_apress_threads_MainActivity_CONTEXT_INCLUDE_CODE
#define com_apress_threads_MainActivity_CONTEXT_INCLUDE_CODE 1L
#undef com_apress_threads_MainActivity_CONTEXT_IGNORE_SECURITY
#define com_apress_threads_MainActivity_CONTEXT_IGNORE_SECURITY 2L
#undef com_apress_threads_MainActivity_CONTEXT_RESTRICTED
#define com_apress_threads_MainActivity_CONTEXT_RESTRICTED 4L
#undef com_apress_threads_MainActivity_RESULT_CANCELED
#define com_apress_threads_MainActivity_RESULT_CANCELED 0L
#undef com_apress_threads_MainActivity_RESULT_OK
#define com_apress_threads_MainActivity_RESULT_OK -1L
#undef com_apress_threads_MainActivity_RESULT_FIRST_USER
#define com_apress_threads_MainActivity_RESULT_FIRST_USER 1L
#undef com_apress_threads_MainActivity_DEFAULT_KEYS_DISABLE
#define com_apress_threads_MainActivity_DEFAULT_KEYS_DISABLE 0L
#undef com_apress_threads_MainActivity_DEFAULT_KEYS_DIALER
#define com_apress_threads_MainActivity_DEFAULT_KEYS_DIALER 1L
#undef com_apress_threads_MainActivity_DEFAULT_KEYS_SHORTCUT
#define com_apress_threads_MainActivity_DEFAULT_KEYS_SHORTCUT 2L
#undef com_apress_threads_MainActivity_DEFAULT_KEYS_SEARCH_LOCAL
#define com_apress_threads_MainActivity_DEFAULT_KEYS_SEARCH_LOCAL 3L
#undef com_apress_threads_MainActivity_DEFAULT_KEYS_SEARCH_GLOBAL
#define com_apress_threads_MainActivity_DEFAULT_KEYS_SEARCH_GLOBAL 4L
/*
 * Class:     com_apress_threads_MainActivity
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_apress_threads_MainActivity_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_apress_threads_MainActivity
 * Method:    nativeFree
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_apress_threads_MainActivity_nativeFree
  (JNIEnv *, jobject);

/*
 * Class:     com_apress_threads_MainActivity
 * Method:    nativeWorker
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_apress_threads_MainActivity_nativeWorker
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_apress_threads_MainActivity
 * Method:    posixThreads
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_apress_threads_MainActivity_posixThreads
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
